Multiple to-do list is mostly done
ukaptelinin/todo_list_1 pull request #11
Opened 2024-06-08 21:09 UTC by ukaptelinin

First version of multiple to-do list

2024-06-10 17:37 UTC, SviatoslavKaptelinin requested changes

2024-06-10 17:37 UTC, SviatoslavKaptelinin commented on src/App.tsx
> +            <Case />
Почему Case?

2024-06-10 17:37 UTC, SviatoslavKaptelinin commented on src/Components/AppHeader/AppHeader.tsx
> +                <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
почему div?

2024-06-10 17:37 UTC, SviatoslavKaptelinin commented on src/Components/InputNewTodo/InputNewTodo.tsx
> +const InputNewTodo: FC = () => {
InputNewTodoList

2024-06-10 17:37 UTC, SviatoslavKaptelinin commented on src/Components/InputNewTodo/InputNewTodo.tsx
> +            inputTitel: '',
inputTitle

2024-06-10 17:37 UTC, SviatoslavKaptelinin commented on src/Components/TodoHeader/TodoHeader.tsx
> +const TodoHeader = (titel:string): JSX.Element => (
FC<{ title: string }>

2024-06-10 17:37 UTC, SviatoslavKaptelinin commented on src/Components/TodoItem/TodoItem.tsx
> +const TodoItem:FC = () => (
TodoListPage

2024-06-10 17:37 UTC, SviatoslavKaptelinin commented on src/Components/TodoItem/TodoItem.tsx
> +    <TodoListStateContext.Provider value={useCurrentTodoListStore()}>
Нврисовать страницу с ошибкой 404 если стора нет

2024-06-10 17:37 UTC, SviatoslavKaptelinin commented on src/Components/TodoItem/useCurrentTodoListStore.ts
> +        throw Error('todoListStore not found!');
не кидать ошибку

2024-06-10 17:37 UTC, SviatoslavKaptelinin commented on src/Components/TodosCardList/TodosCardItem/TodosCardItem.tsx
> +const TodosCardItem:FC<TodoListStore> = ({ id, title }) => {
FC<{ id: number, title: string }>

2024-06-10 17:37 UTC, SviatoslavKaptelinin commented on src/Hooks/useCurrentTodoUrl.ts
> +import { ID, TITEL } from '../constants';
убрать

2024-06-10 17:37 UTC, SviatoslavKaptelinin commented on src/Stores/TodoListStore.ts
> +// import { TodosStore } from './TodosStore';
убрать комментарий

2024-06-10 17:37 UTC, SviatoslavKaptelinin commented on src/Stores/TodoListStore.ts
>  });
configure перенести в центральный стор

2024-06-10 17:37 UTC, SviatoslavKaptelinin commented on src/Stores/TodoListStore.ts
> +// }
убрать

2024-06-10 17:37 UTC, SviatoslavKaptelinin commented on src/Stores/TodoListStore.ts
> +    // };
убрать

2024-06-10 17:37 UTC, SviatoslavKaptelinin commented on src/Stores/TodosStore.ts
> +    // autorun,
убрать

2024-06-10 17:37 UTC, SviatoslavKaptelinin commented on src/Stores/TodosStore.ts
> +// }
убрать

2024-06-10 17:37 UTC, SviatoslavKaptelinin commented on src/Stores/TodosStore.ts
> +    }; */
убрать

2024-06-10 17:37 UTC, SviatoslavKaptelinin commented on src/Stores/TodosStore.ts
> +    }; */
убрать

2024-06-10 18:12 UTC, ukaptelinin commented on src/Components/TodoHeader/TodoHeader.tsx
> +const TodoHeader = (titel:string): JSX.Element => (
Исправил, я эту компонету не испоьзовал, теперь вставил. Пропс вообще не нужен. Через useContext title получаю.

2024-06-17 16:47 UTC, SviatoslavKaptelinin requested changes

2024-06-17 16:47 UTC, SviatoslavKaptelinin commented on src/Components/ErrorPage/ErrorPage.tsx
> +            {errorcode}
имена переменных в camelCase

2024-06-17 16:47 UTC, SviatoslavKaptelinin commented on src/Components/RootRoutes/RootRoutes.tsx
> +        <Route path="/todo_list_1" Component={Main} />
todo_list_1 не несет никакого смысла. Можно либо /main, либо просто /

2024-06-17 16:47 UTC, SviatoslavKaptelinin commented on src/Components/RootRoutes/RootRoutes.tsx
> +        <Route path="/todoitem/:id" Component={TodoListPage} />
todoitem - это пункт списка. Здесь должен быть список. Еще урлы желательно короткими делать, можно просто /list

2024-06-17 16:47 UTC, SviatoslavKaptelinin commented on src/Components/TodoListPage/useCurrentTodoListStore.ts
> +const useCurrentTodoListStore = () :TodoListStore => {
usePageTodoListStore, current в данном случае непонятно что обозначает

2024-06-17 16:47 UTC, SviatoslavKaptelinin commented on src/Components/TodosCardList/TodosCardItem/TodosCardItem.tsx
> +
Убрать разрыв строки

2024-06-17 16:53 UTC, ukaptelinin commented on src/Components/RootRoutes/RootRoutes.tsx
> +        <Route path="/todo_list_1" Component={Main} />
Это временная мера. Когда я сделал деплой, по другому не работает. А так, конечно "/".

2024-06-17 17:40 UTC, SviatoslavKaptelinin approved these changes

2024-06-17 18:32 UTC, merged